import type { Prompt } from "@prisma/client";

type DemoPrompt = Pick<Prompt, "id" | "title" | "tags" | "body">;

export const DEMO_PROMPTS: DemoPrompt[] = [
  {
    id: "demo-codex-impl-request",
    title: "Codex依頼：小さく安全に実装（E2E込み）",
    tags: ["demo", "codex", "dev"],
    body: [
      "以下の改善タスクを「小さく安全に」実装して。",
      "",
      "## Goal",
      "{{goal_text}}",
      "",
      "## Acceptance（期待する状態）",
      "{{acceptance_details}}",
      "",
      "## Current（現状）",
      "{{current_text}}",
      "",
      "## Constraints（制約）",
      "{{constraints_details}}",
      "",
      "## Attachments（関連ファイル/ログ）",
      "{{code_text}}",
      "{{error_logs}}",
      "",
      "## Process（手順）",
      "1. 変更点を最小差分に分割して提案してから着手",
      "2. 実装 → `pnpm biome:check` → `pnpm build`",
      "3. E2E（Playwright）を含めた回帰確認",
      "4. 落ちたら直して通すまで",
      "5. 変更理由・影響範囲・テスト観点をPR本文用に要約",
    ].join("\n"),
  },

  {
    id: "demo-bug-triage",
    title: "BUG切り分けテンプレ（最初の10分）",
    tags: ["demo", "bug", "triage"],
    body: [
      "## ゴール",
      "{{goal_text}}",
      "",
      "## 現象",
      "{{current_text}}",
      "",
      "## 期待する挙動",
      "{{acceptance_details}}",
      "",
      "## エラーログ",
      "{{error_logs}}",
      "",
      "## 追加情報",
      "- 直前に変えた点: {{change_text}}",
      "- 再現手順: {{steps_text}}",
    ].join("\n"),
  },

  {
    id: "demo-pr-review",
    title: "PRレビュー依頼（最短で通す）",
    tags: ["demo", "pr", "review"],
    body: [
      "## 目的",
      "{{goal_text}}",
      "",
      "## 変更内容（要約）",
      "{{current_text}}",
      "",
      "## 受け入れ条件",
      "{{acceptance_details}}",
      "",
      "## 影響範囲（変更ファイル/導線）",
      "{{constraints_details}}",
      "",
      "## レビュー観点",
      "- 仕様と整合しているか",
      "- 例外/エラー時の挙動",
      "- テストの更新漏れ",
    ].join("\n"),
  },

  {
    id: "demo-e2e-fail",
    title: "Playwright E2E失敗の調査テンプレ",
    tags: ["demo", "e2e", "playwright"],
    body: [
      "## 失敗概要",
      "{{current_text}}",
      "",
      "## 失敗ログ（重要部分だけ）",
      "{{error_logs}}",
      "",
      "## 直近変更",
      "{{change_text}}",
      "",
      "## 期待する修正方針",
      "{{goal_text}}",
      "",
      "## チェックリスト",
      "- selector は data-pv / getByTestId に寄せたか",
      "- 文言依存になっていないか",
      "- waitForTimeout で誤魔化していないか",
    ].join("\n"),
  },

  {
    id: "demo-dependabot-grouped",
    title: "Dependabot（Grouped）対応：安全にまとめて上げる",
    tags: ["demo", "deps", "dependabot"],
    body: [
      "## ゴール",
      "{{goal_text}}",
      "",
      "## 現状",
      "{{current_text}}",
      "",
      "## 受け入れ条件（Acceptance）",
      "{{acceptance_details}}",
      "",
      "## 制約",
      "{{constraints_details}}",
      "",
      "## 手順（プロトコル）",
      "1. 影響範囲を洗い出す（lockfile / runtime deps / dev deps）",
      "2. まず security updates（grouped）を適用し、PR数を抑える",
      "3. `pnpm install` → `pnpm biome:check` → `pnpm build` → `pnpm test:e2e` を通す",
      "4. 失敗したら原因を切り分け、最小差分で修正して通すまで",
      "5. PR本文に「更新理由 / 影響範囲 / 回帰確認」を明記する",
      "",
      "## エラーログ",
      "{{error_logs}}",
    ].join("\n"),
  },

  {
    id: "demo-config-where-and-how",
    title: "CONFIG：キー/設定どこ？（場所・手順）",
    tags: ["config", "setup", "env"],
    body: [
      "{{service}} で {{item}} の「場所」と「正しい設定手順」が分からない。",
      "省略せずに、クリック手順/画面遷移/入力例まで具体的に案内して。",
      "",
      "# 1) 前提",
      "- サービス：{{service}}（例：Supabase / Vercel / GitHub / Auth0 / Cloudflare / Stripe）",
      "- 何を探してる？：{{item}}（例：API Key / Project URL / Webhook Secret / env var / callback URL / deploy key）",
      "- 目的：（例：ローカル実行、Supabase設定、Vercelデプロイ、GitHub Actions、OAuth連携、Webhook受信）",
      "- いま困ってること：{{problem}}",
      "- 今見えている画面/メニュー：添付ファイル（あれば）",
      "",
      "# 2) 求める出力（この順番で）",
      "1. 「その設定がある場所」への最短手順（クリック手順を省略しない）",
      "2. そこで何を入力/コピペするか（サンプル値の形式、例も）",
      "3. それを「どこに置くべきか」（.env.local / Vercel Environment Variables / GitHub Secrets / 管理画面 等）",
      "4. 動作確認の方法（確認ポイント、簡単なテスト）",
      "5. よくある落とし穴（権限不足、間違ったキー種別、公開してはいけない情報、反映タイミング）",
      "",
      "# 3) 制約",
      "- 分からない情報があれば、最初に質問は「最大3つ」まで。",
      "- ただし推測できるなら質問なしで進めてOK。",
      "- セキュリティ注意：公開してはいけない値（秘密鍵/トークン等）がある場合は明示して。",
    ].join("\n"),
  },
];
